L6 t0 data
beblowska/future-collars pull request #26
Opened 2023-08-19 19:02 UTC by beblowska

Napisz program, którego zadaniem będzie stworzeniu pliku data.txt z zawartością:

2023-08-20 18:54 UTC, patryk-stepniak requested changes

2023-08-20 18:54 UTC, patryk-stepniak commented on src/main/java/task60/Main.java
> +    } catch (IOException e) {
formatowanie się rozjechało

2023-08-20 18:54 UTC, patryk-stepniak commented on src/main/java/task60/Main.java
> +        boolean exists = file.exists();
te zmienne nie są nigdzie używane

2023-08-20 18:54 UTC, patryk-stepniak commented on src/main/java/task60/Main.java
> +        File file = new File("src/main/resources/data.txt");
ta zmienna również nie jest wykorzystywana

2023-08-20 18:54 UTC, patryk-stepniak commented on src/main/java/task60/Main.java
> +        try (BufferedWriter writer = new BufferedWriter(new FileWriter("data.txt"))) {
Wynieś ten kod do osobnej klasy, np. FileWriter, która będzie miała metodę odpowiedzialną za zapis danych do pliku. Najlepiej, aby ta metoda przyjmowała tekst, który ma zapisać oraz ścieżkę do pliku.

2023-09-08 08:01 UTC, marwis1995 approved these changes

2023-09-08 08:01 UTC, merged