L6 T4 Word search
beblowska/future-collars pull request #30
Opened 2023-08-20 12:57 UTC by beblowska

Zaimplementuj klasę, której zadaniem będzie przeczytanie pliku data.txt oraz wyszukanie w przeczytanym tekście zadanego słowa.

2023-08-21 14:38 UTC, patryk-stepniak requested changes

2023-08-21 14:38 UTC, patryk-stepniak commented on src/main/java/task64/WordSearch.java
> +                    System.out.println("Word found " + wordCount + " times.");
Realizuj to wyświetlenie dopiero jak policzysz wszystkie wystąpienia danego słowa.
Obecnie wyświetlasz ten tekst za każdym razem, gdy je odnajdziesz czego wynikiem będzie np.

Word found 1 times.
Word found 2 times.
Word found 3 times.
..
..
..
Word found N times.

2023-08-21 14:38 UTC, patryk-stepniak commented on src/main/java/task64/WordSearch.java
> +    public static void main(String[] args) {
Analogicznie jak poprzednio: zamiast main'a dajmu w tej klasie metodę, którą będzie można wykorzystać w różnych miejscach kodu.

2023-09-08 08:28 UTC, marwis1995 approved these changes

2023-09-08 08:28 UTC, merged