L6 T6 To upper case
beblowska/future-collars pull request #32
Opened 2023-08-21 12:18 UTC by beblowska

Zaimplementuj klasę, której zadaniem będzie przeczytanie pliku data.txt oraz zamianę tekstu na wielkie litery. Wynik konwersji powinien zostać zapisany do pliku output.txt.

2023-08-21 14:53 UTC, patryk-stepniak requested changes

2023-08-21 14:53 UTC, patryk-stepniak commented on src/main/java/task66/ConvertToUpperCase.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(inputFilePath))) {
Zamiast robic try w try spróbuj przerobić kod tak, aby był czytelniejszy. 
Moja propozycja jest następująca:

Spraw, aby twoja główna metoda wyglądała następująco:

{
   List<String> lines = readLines(inputFilePath);
   List<String> uppercasedLines = mapToUppercase(lines);
   saveLines(outputFilePath, uppercasedLines);
}

Twój kod będzie o wiele czytelniejszy.
Pozostałe metody oczywiście będą metodami pomocniczymi, więc powinny zostać prywatne.

2023-08-21 14:53 UTC, patryk-stepniak commented on src/main/java/task66/ConvertToUpperCase.java
> +    public static void main(String[] args) {
Przy okazji poniższej poprawki można pozbyć się tego maina na rzecz zwykłej metody :)

2023-09-08 08:51 UTC, marwis1995 approved these changes

2023-09-08 08:51 UTC, merged