L2 age verification
beblowska/future-collars pull request #5
Opened 2023-06-29 20:22 UTC by beblowska

weryfikacja czy podany wiek jest większy bądź równy 18 + testy jednostkowe

2023-07-03 08:28 UTC, patryk-stepniak requested changes
Rozwiąż proszę konflikty i spraw, by PR zawierał tylko pliki związane z tym zadaniem. (obecnie ten PR wprowadza wiele dodatkowych, a niepotrzebnych plików).

2023-08-02 08:38 UTC, patryk-stepniak requested changes

2023-08-02 08:38 UTC, patryk-stepniak commented on src/test/java/project/AgeVerificationTest.java
> +        assertTrue(verifier.isAgeValid(18));
Niepotrzebnie sprawdzasz tę samą rzecz trzy razy. Wystarczy raz :)

2023-08-02 08:38 UTC, patryk-stepniak commented on src/test/java/project/AgeVerificationTest.java
> +        assertTrue(verifier.isAgeValid(18));
Tak samo w drugim teście

2023-08-09 19:52 UTC, DamianMarek98 commented on src/test/java/task24/AgeVerificationTest.java
> +public class AgeVerificationTest {
Nie potrzebujesz drugiej klasy testującej dokładnie to samo co powyższa. Klasa z pakietu `project;` może zostać usunięta.

2023-08-09 19:56 UTC, DamianMarek98 requested changes
Usuń jedną z klas AgeVerificationTest

2023-08-30 20:19 UTC, merged